/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author LAB03M05
 */
public class Jokenpo_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Jokenpo_GUI
     */
    public Jokenpo_GUI() {
        initComponents();
        PapelBot.setVisible(false);
        PedraBot.setVisible(false);
        TesouraBot.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tesoura = new org.edisoncor.gui.panel.PanelImage();
        papel = new org.edisoncor.gui.panel.PanelImage();
        pedra = new org.edisoncor.gui.panel.PanelImage();
        PedraBot = new org.edisoncor.gui.panel.PanelImage();
        PapelBot = new org.edisoncor.gui.panel.PanelImage();
        TesouraBot = new org.edisoncor.gui.panel.PanelImage();
        TesouraButton = new javax.swing.JButton();
        PapelButton = new javax.swing.JButton();
        PedraButton = new javax.swing.JButton();
        PontPlayer = new javax.swing.JLabel();
        PontBot = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(300, 400));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        tesoura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/tesoura.png"))); // NOI18N

        javax.swing.GroupLayout tesouraLayout = new javax.swing.GroupLayout(tesoura);
        tesoura.setLayout(tesouraLayout);
        tesouraLayout.setHorizontalGroup(
            tesouraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        tesouraLayout.setVerticalGroup(
            tesouraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(tesoura);
        tesoura.setBounds(40, 30, 100, 100);

        papel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/papel.png"))); // NOI18N

        javax.swing.GroupLayout papelLayout = new javax.swing.GroupLayout(papel);
        papel.setLayout(papelLayout);
        papelLayout.setHorizontalGroup(
            papelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        papelLayout.setVerticalGroup(
            papelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(papel);
        papel.setBounds(220, 30, 100, 100);

        pedra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/pedra.png"))); // NOI18N

        javax.swing.GroupLayout pedraLayout = new javax.swing.GroupLayout(pedra);
        pedra.setLayout(pedraLayout);
        pedraLayout.setHorizontalGroup(
            pedraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pedraLayout.setVerticalGroup(
            pedraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(pedra);
        pedra.setBounds(390, 30, 100, 100);

        PedraBot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/pedra.png"))); // NOI18N

        javax.swing.GroupLayout PedraBotLayout = new javax.swing.GroupLayout(PedraBot);
        PedraBot.setLayout(PedraBotLayout);
        PedraBotLayout.setHorizontalGroup(
            PedraBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        PedraBotLayout.setVerticalGroup(
            PedraBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(PedraBot);
        PedraBot.setBounds(390, 230, 100, 100);

        PapelBot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/papel.png"))); // NOI18N

        javax.swing.GroupLayout PapelBotLayout = new javax.swing.GroupLayout(PapelBot);
        PapelBot.setLayout(PapelBotLayout);
        PapelBotLayout.setHorizontalGroup(
            PapelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        PapelBotLayout.setVerticalGroup(
            PapelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(PapelBot);
        PapelBot.setBounds(220, 230, 100, 100);

        TesouraBot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/tesoura.png"))); // NOI18N

        javax.swing.GroupLayout TesouraBotLayout = new javax.swing.GroupLayout(TesouraBot);
        TesouraBot.setLayout(TesouraBotLayout);
        TesouraBotLayout.setHorizontalGroup(
            TesouraBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        TesouraBotLayout.setVerticalGroup(
            TesouraBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(TesouraBot);
        TesouraBot.setBounds(40, 230, 100, 100);

        TesouraButton.setText("Tesoura");
        jPanel1.add(TesouraButton);
        TesouraButton.setBounds(40, 133, 100, 30);

        PapelButton.setText("Papel");
        jPanel1.add(PapelButton);
        PapelButton.setBounds(220, 133, 100, 30);

        PedraButton.setText("Pedra");
        jPanel1.add(PedraButton);
        PedraButton.setBounds(390, 133, 100, 30);
        jPanel1.add(PontPlayer);
        PontPlayer.setBounds(540, 100, 0, 0);
        jPanel1.add(PontBot);
        PontBot.setBounds(540, 250, 0, 0);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 600, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jokenpo_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jokenpo_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jokenpo_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jokenpo_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jokenpo_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.panel.PanelImage PapelBot;
    private javax.swing.JButton PapelButton;
    private org.edisoncor.gui.panel.PanelImage PedraBot;
    private javax.swing.JButton PedraButton;
    private javax.swing.JLabel PontBot;
    private javax.swing.JLabel PontPlayer;
    private org.edisoncor.gui.panel.PanelImage TesouraBot;
    private javax.swing.JButton TesouraButton;
    private javax.swing.JPanel jPanel1;
    private org.edisoncor.gui.panel.PanelImage papel;
    private org.edisoncor.gui.panel.PanelImage pedra;
    private org.edisoncor.gui.panel.PanelImage tesoura;
    // End of variables declaration//GEN-END:variables
}
